# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UwatIZpmbrkRG5xhoR7LXNQcb68akrJu
"""

import numpy as np
from skimage import io
photo = io.imread('https://images-na.ssl-images-amazon.com/images/I/81KA4Aty8xL._SL1000_.jpg')
type(photo)

photo.shape

import matplotlib.pyplot as plt
plt.imshow(photo)

photo_new=np.where(photo>-1,255-photo,0)
plt.imshow(photo_new)

io.imsave('final.jpg',photo_new)